name = "sorascore-streams-api"
main = "worker.js"
compatibility_date = "2024-03-20"

# This connects the Worker to your D1 Database
[[d1_databases]]
binding = "DB"
database_name = "sorascore_streams"
database_id = "b54229f9-bc96-47f3-bbbf-c4556955c231"
